### PR TITLE
Code challenge work

### PR DESCRIPTION
**Pull request by qiheme**
I tried to add logic for the emails but I have hit a rut...

### CODE REVIEW

**Comment by ChrisCPO** [comment]
@qiheme I decided to rename this repo, also I am not familiar with mail gun but I have used action mailer, with the gem letter_opener in the development group this will open outgoing emails in the browser so you can test them.

also I curious as to what your goal is with this?

**Comment by qiheme** [comment]
I'm not I understand your question...do you mean with the gem I used?

**Comment by ChrisCPO** [comment]
No, I'am just curious as to why your submitting a pr to some random project of mine lol?

**Comment by qiheme** [comment]
Oh, I thought this was the repo for the code challenge for Cipher Health?

**Pull request closed without merging**
